name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload built JAR
        uses: actions/upload-artifact@v3
        with:
          name: 'oculus-artifacts'
          path: build/libs